print("           ^")
print("          / |")
print("         /  |")
print("        /   |")
print("       /    |")
print("      /     |")
print("     /      |")
print("    /       |")
print("   /        |")
print("  /         |")
print(" /          |")
print("/___________|")